reservas_homepage:
    path:     /
    defaults: { _controller: reservasBundle:Client:index }
reservas_api:
    path: /api
    defaults: {_controller: reservasBundle:Api:index}
reservas_api_reservas:
    path: /api/reservas
    defaults: {_controller: reservasBundle:Api:reservas}
reservas_api_servicios:
    path: /api/servicios
    defaults: {_controller: reservasBundle:Api:servicios}
reservas_api_lista_negra:
    path: /api/listanegra
    defaults: {_controller: reservasBundle:Api:listaNegra}
reservas_api_menu:
    path: /api/menu
    defaults: {_controller: reservasBundle:Api:menu}
reservas_api_alergenos:
    path: /api/alergenos
    defaults: {_controller: reservasBundle:Api:alergenos}
reservas_api_correos:
    path: /api/correos
    defaults: {_controller: reservasBundle:Api:correos}
reservas_api_plantillas:
    path: /api/plantillas
    defaults: {_controller: reservasBundle:Api:misPlantillas}
