reservas_homepage:
    path:     /
    defaults: { _controller: reservasBundle:Client:index }
reservas_client_reservas:
    path: /reservas
    defaults: {_controller: reservasBundle:Client:reservas }
reservas_client_consultar:
    path: /consultar
    defaults: {_controller: reservasBundle:Client:consultar }
reservas_client_reservas_pdf:
    path: /pdf/{id}
    defaults: {_controller: reservasBundle:Client:pdfreservas}

reservas_admin:
    path: /admin
    defaults: {_controller: reservasBundle:Admin:index }
reservas_admin_config:
    path: /admin/config
    defaults: {_controller: reservasBundle:Admin:config }
reservas_api:
    path: /api
    defaults: {_controller: reservasBundle:Api:index}
reservas_api_reservas:
    path: /api/reservas
    defaults: {_controller: reservasBundle:Api:reservas}
reservas_api_reservas_plazas:
    path: /api/reservas/plazas
    defaults: {_controller: reservasBundle:Api:plazasrestantes}
    methods: POST
reservas_api_reservas_alergenos:
    path: /api/reservas/alergenos
    defaults: {_controller: reservasBundle:Api:alergenosbyreserva}
    methods: POST
reservas_api_reservas_codreserva:
    path: /api/reservas/codreserva
    defaults: {_controller: reservasBundle:Api:reservabycodreserva}
    methods: POST
reservas_api_reservar_add:
    path: /api/reservas/add
    defaults: {_controller: reservasBundle:Api:addreservas}
    methods: POST
reservas_api_reservar_edit:
    path: /api/reservas/edit
    defaults: {_controller: reservasBundle:Api:editreservas}
    methods: POST
reservas_api_reservar_delete:
    path: /api/reservas/delete
    defaults: {_controller: reservasBundle:Api:deletereservas}
    methods: POST
reservas_api_servicios:
    path: /api/servicios
    defaults: {_controller: reservasBundle:Api:servicios}
reservas_api_servicios_fecha:
  path: /api/servicios/fecha
  defaults: {_controller: reservasBundle:Api:serviciosbyfecha}
  methods: POST
reservas_api_servicios_id:
    path: /api/servicios/id
    defaults: {_controller: reservasBundle:Api:serviciosbyid}
    methods: POST
reservas_api_servicios_add:
    path: /api/servicios/add
    defaults: {_controller: reservasBundle:Api:addservicios}
    methods: POST
reservas_api_servicios_edit:
    path: /api/servicios/edit
    defaults: {_controller: reservasBundle:Api:editservicios}
    methods: POST
reservas_api_lista_negra:
    path: /api/listanegra
    defaults: {_controller: reservasBundle:Api:listaNegra}
reservas_api_menu:
    path: /api/menu
    defaults: {_controller: reservasBundle:Api:menu}
reservas_api_menu_add:
    path: /api/menu/add
    defaults: {_controller: reservasBundle:Api:addmenu}
reservas_api_menu_edit:
    path: /api/menu/edit
    defaults: {_controller: reservasBundle:Api:editmenu}
reservas_api_alergenos:
    path: /api/alergenos
    defaults: {_controller: reservasBundle:Api:alergenos}
reservas_api_correos:
    path: /api/correos
    defaults: {_controller: reservasBundle:Api:correos}
reservas_api_correos_add:
    path: /api/correos/add
    defaults: {_controller: reservasBundle:Api:addcorreos}
reservas_api_correos_edit:
    path: /api/correos/edit
    defaults: {_controller: reservasBundle:Api:editcorreos}
reservas_api_plantillas:
    path: /api/plantillas
    defaults: {_controller: reservasBundle:Api:misPlantillas}
reservas_api_plantillas_add:
    path: /api/plantillas/add
    defaults: {_controller: reservasBundle:Api:addplantillas}
reservas_api_plantillas_edit:
    path: /api/plantillas/edit
    defaults: {_controller: reservasBundle:Api:editplantillas}
