reservasBundle\Entity\Config:
    type: entity
    table: null
    repositoryClass: reservasBundle\Repository\ConfigRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        confirmacion:
            type: text
        recordatorio:
            type: text
        clistaespera:
            type: text
        cancelacion:
            type: text
        edicionservicio:
            type: text
        edicionreserva:
            type: text

    lifecycleCallbacks: {  }
