reservasBundle\Entity\Misplantillas:
    type: entity
    table: MisPlantillas
    id:
        idmisplantillas:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idMisPlantillas
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        asunto:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Asunto
    lifecycleCallbacks: {  }
