reservasBundle\Entity\Servicios:
    type: entity
    table: Servicios
    repositoryClass: reservasBundle\Entity\ServiciosRepository
    indexes:
        fk_Servicios_Menu1_idx:
            columns:
                - Menu_idMenu
    id:
        idservicios:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idServicios
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: Nombre

        fechaservicio:
            type: datetime
            nullable: true
            column: FechaServicio
        plazas:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Plazas
        plazasocupadas:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PlazasOcupadas
        avisoenviado:
            type: boolean
    manyToOne:
        menumenu:
            targetEntity: Menu
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Menu_idMenu:
                    referencedColumnName: idMenu
            orphanRemoval: false
    lifecycleCallbacks: {  }
